### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by JakobDev** [Stabyourself/mari0#44]
I created a [Flatpak](https://flatpak.org) for Mari0. If you don't know what Flatpaks are, you can think of it like Docker, but for Linux Desktop Apps. Flatpaks can be published on [Flathub](https://flathub.org), which allows a one click installation on most Linux Distros. You need these files to build:

net.stabyourself.Mari0:
```yaml
id: net.stabyourself.Mari0
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: mari0
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --device=all
  - --share=ipc
  - --share=network
  - --socket=pulseaudio

modules:
  - name: luajit
    no-autogen: true
    make-install-args:
      - PREFIX=/app
    sources:
      - type: archive
        url: https://luajit.org/download/LuaJIT-2.1.0-beta3.tar.gz
        sha256: 1ad2e34b111c802f9d0cdf019e986909123237a28c746b21295b63c9e785d9c3
        x-checker-data:
            type: anitya
            project-id: 6444
            stable-only: false
            url-template: https://luajit.org/download/LuaJIT-$version.tar.gz
    cleanup:
      - /share/man
      - /include

  - name: libmodplug
    sources:
      - type: archive
        url: https://downloads.sourceforge.net/modplug-xmms/libmodplug-0.8.9.0.tar.gz
        sha256: 457ca5a6c179656d66c01505c0d95fafaead4329b9dbaa0f997d00a3508ad9de
        x-checker-data:
            type: anitya
            project-id: 5669
            url-template: https://downloads.sourceforge.net/modplug-xmms/libmodplug-$version.tar.gz
    cleanup:
      - /include

  - name: love2d
    sources:
      - type: archive
        url: https://github.com/love2d/love/releases/download/11.4/love-11.4-linux-src.tar.gz
        sha256: e32feecaf5f4f210242a4b5f26cdf9ce9014bfde18d51286f643bb7fe51f5369
        x-checker-data:
            type: json
            url: https://api.github.com/repos/love2d/love/releases/latest
            version-query: .tag_name
            url-query: .assets[] | select(.name | test ("^.+linux-src\\.tar\\.gz$")) | .browser_download_url
    cleanup:
      - /share

  - name: Mari0
    buildsystem: simple
    build-commands:
      - mkdir -p $FLATPAK_DEST/Mari0
      - cp -r source/* $FLATPAK_DEST/Mari0
      - install -Dm755 mari0.sh $FLATPAK_DEST/bin/mari0
      - install -Dm644 source/graphics/icon.png $FLATPAK_DEST/share/icons/hicolor/32x32/apps/$FLATPAK_ID.png
      - install -Dm644 source/_DO_NOT_INCLUDE/icon.png $FLATPAK_DEST/share/icons/hicolor/512x512/apps/$FLATPAK_ID.png
      - install -Dm644 net.stabyourself.Mari0.desktop -t $FLATPAK_DEST/share/applications
      - install -Dm644 net.stabyourself.Mari0.metainfo.xml -t $FLATPAK_DEST/share/metainfo
    sources:
      - type: git
        dest: source
        url: https://github.com/Stabyourself/mari0.git
        commit: 46c473668a975978e197455ca29d4d890454d3c0
        tag: 1.6.2
        x-checker-data:
            type: git
      - type: script
        dest-filename: mari0.sh
        commands:
          - exec love /app/Mari0
      - type: file
        path: net.stabyourself.Mari0.desktop
      - type: file
        path: net.stabyourself.Mari0.metainfo.xml
```

net.stabyourself.Mari0.desktop
```desktop
# Created with jdDesktopEntryEdit 1.1
[Desktop Entry]
Type=Application
Name=Mari0
Comment=Mario + Portal platformer
Icon=net.stabyourself.Mari0
TryExec=mari0
Exec=mari0
Categories=Game;ActionGame;
Keywords=love2d;
SingleMainWindow=true
```

net.stabyourself.Mari0.metainfo.xml
```xml
<?xml version='1.0' encoding='utf-8'?>
<component type="desktop">
  <!--Created with jdAppStreamEdit 7.0-->
  <id>net.stabyourself.Mari0</id>
  <name>Mari0</name>
  <summary>Mario + Portal platformer</summary>
  <developer_name>Stabyourself</developer_name>
  <launchable type="desktop-id">net.stabyourself.Mari0.desktop</launchable>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>MIT</project_license>
  <description>
    <p>Two genre defining games from completely different eras: Nintendo's Super Mario Bros. and Valve's Portal. These two games managed to give Platformers and First-Person Puzzle Games a solid place in the video game world. But what if Nintendo teamed up with Valve and recreated the famous Mario game with Portal gun mechanics?</p>
    <p>Features:</p>
    <ul>
      <li>Complete recreation of SMB</li>
      <li>Elements from Portal</li>
      <li>Portal gun that shoots portals</li>
      <li>4-player simultaneous coop</li>
      <li>Level Editor that was used to create the levels in the game</li>
      <li>33 different hats</li>
      <li>Downloadable Mappacks</li>
      <li>Game modifiers for extra fun</li>
    </ul>
  </description>
  <screenshots>
    <screenshot type="default">
      <image type="source">https://stabyourself.net/images/screenshots/mari0-thumb1.png</image>
    </screenshot>
    <screenshot>
      <image type="source">https://stabyourself.net/images/screenshots/mari0-thumb2.png</image>
    </screenshot>
    <screenshot>
      <image type="source">https://stabyourself.net/images/screenshots/mari0-thumb3.png</image>
    </screenshot>
    <screenshot>
      <image type="source">https://stabyourself.net/images/screenshots/mari0-thumb4.png</image>
    </screenshot>
    <screenshot>
      <image type="source">https://stabyourself.net/images/screenshots/mari0-thumb5.png</image>
    </screenshot>
  </screenshots>
  <releases>
    <release version="1.6.2" date="2018-09-15" type="stable">
      <url>https://github.com/Stabyourself/mari0/releases/tag/1.6.2</url>
      <description>
        <ul>
          <li>LÖVE 11.1 support, thanks to Noahkiq and WillWare</li>
        </ul>
      </description>
    </release>
    <release version="1.6.1" date="2016-12-20" type="stable">
      <url>https://github.com/Stabyourself/mari0/releases/tag/v1.6.1</url>
    </release>
    <release version="1.6" date="2016-12-20" type="stable">
      <url>https://github.com/Stabyourself/mari0/releases/tag/v1.6</url>
    </release>
  </releases>
  <url type="homepage">https://stabyourself.net/mari0</url>
  <url type="bugtracker">https://github.com/Stabyourself/mari0/issues</url>
  <url type="vcs-browser">https://github.com/Stabyourself/mari0</url>
  <categories>
    <category>Game</category>
    <category>ActionGame</category>
  </categories>
  <recommends>
    <control>gamepad</control>
  </recommends>
  <supports>
    <control>pointing</control>
    <control>keyboard</control>
  </supports>
  <content_rating type="oars-1.1">
    <content_attribute id="violence-cartoon">mild</content_attribute>
  </content_rating>
  <provides>
    <binary>mari0</binary>
  </provides>
  <keywords>
    <keyword>love2d</keyword>
  </keywords>
</component>
```

Tell me, if you are interested in a Flatpak. If you do not want to maintain the Flatpak, I can do it for you.
